

[goldberg]
download_url = "https://github.com/Detanup01/gbe_fork/releases/latest/download/emu-win-release.7z"

[aoe2]
steam_folder = "AoE2DE"
gh_companion_user = "luskaner"
gh_companion_repo = "ageLANServerLauncherCompanion"
gh_launcher_user = "luskaner"
gh_launcher_repo = "ageLANServer"
