[package]
name = "launch"
version = "0.1.0"
edition = "2024"

[dependencies]
aes-gcm.workspace = true
common.workspace = true
rust-ini.workspace = true
anyhow.workspace = true

[build-dependencies]
winresource.workspace = true
